Fix mkdep for dynamic library version (bug #3497)
git-svn-id: https://origsvn.digium.com/svn/libpri/trunk@186 2fbb986a-6c06-0410-b554-c9c1f0a7f128

diff --git a/mkdep b/mkdep
--- a/mkdep
+++ b/mkdep
@@ -100,10 +100,22 @@ if [ $append = 1 ]; then
 		rm -rf $DTMP
 		exit 1
 	fi
-else
-	mv $TMP $D
+	cat $TMP | sed -e 's/\.o:/.lo:/g' >>$D
 	if [ $? != 0 ]; then
-		echo 'mkdep: rename failed.'
+		echo 'mkdep: append failed.'
+		rm -rf $DTMP
+		exit 1
+	fi
+else
+	cat $TMP > $D
+	if [ $? != 0 ]; then
+		echo 'mkdep: overwrite failed.'
+		rm -rf $DTMP
+		exit 1
+	fi
+	cat $TMP | sed -e 's/\.o:/.lo:/g' >>$D
+	if [ $? != 0 ]; then
+		echo 'mkdep: append failed.'
 		rm -rf $DTMP
 		exit 1
 	fi
